import { Question, CandidateSubmission, CandidateAnswer, AssessmentStatus, EmailNotification } from '../types';

export const CREATOR_ACCESS_CODE = 'I_Love_Honey';
export const CANDIDATE_ACCESS_CODE = '#B3L2H100%';

export const DEFAULT_QUESTIONS: Question[] = [
  // ==================== 11TH STANDARD TN STATE BOARD CS (C++ & CORE CONCEPTS) ====================
  {
    id: 'q1',
    qNumber: 1,
    syllabusStandard: '11th',
    topic: 'C++ Tokens, Operators & Precedence',
    language: 'C++',
    title: 'Question 1: C++ Prefix & Postfix Increment Operators',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int a = 5, b = 10, c;
    c = ++a * b--;
    cout << "a = " << a << ", b = " << b << ", c = " << c << endl;
    return 0;
}`,
    description: 'Analyze the C++ code snippet above according to standard operator precedence and side effects. What will be printed on the standard output console?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'a = 6, b = 9, c = 60',
      'a = 5, b = 10, c = 50',
      'a = 6, b = 9, c = 54',
      'a = 6, b = 10, c = 60'
    ],
    correctOptionIndex: 0,
    explanation: '`++a` pre-increments `a` from 5 to 6 first. Then `6 * 10 = 60` is assigned to `c`. Finally, postfix `b--` decrements `b` from 10 to 9.',
    hint: 'Remember: prefix ++ happens before multiplication, postfix -- happens after the evaluation of the expression.'
  },
  {
    id: 'q2',
    qNumber: 2,
    syllabusStandard: '11th',
    topic: 'C++ Control Structures: Switch-Case Fallthrough',
    language: 'C++',
    title: 'Question 2: Switch-Case without Break Statements',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int val = 2, sum = 0;
    switch (val) {
        case 1: sum += 10;
        case 2: sum += 20;
        case 3: sum += 30;
        default: sum += 5;
    }
    cout << "Sum = " << sum << endl;
    return 0;
}`,
    description: 'In Tamil Nadu 11th CS Chapter 10 (Flow of Control), what is the output of the switch-case construct when `break` statements are omitted?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Sum = 20',
      'Sum = 55',
      'Sum = 50',
      'Sum = 65'
    ],
    correctOptionIndex: 1,
    explanation: 'Because val is 2, execution jumps to case 2 (`sum += 20`). Since there are no break statements, execution falls through case 3 (`sum += 30`) and default (`sum += 5`), totaling 20 + 30 + 5 = 55.',
    hint: 'When a matching case lacks a break statement, fall-through occurs into all subsequent cases.'
  },
  {
    id: 'q3',
    qNumber: 3,
    syllabusStandard: '11th',
    topic: 'C++ Functions: Call by Reference with Alias',
    language: 'C++',
    title: 'Question 3: Reference Parameters vs Value Passing',
    codeSnippet: `#include <iostream>
using namespace std;

void modify(int &x, int y) {
    x = x + 10;
    y = y + 20;
}

int main() {
    int p = 5, q = 15;
    modify(p, q);
    cout << p << " " << q << endl;
    return 0;
}`,
    description: 'Examine the function `modify(int &x, int y)`. Predict the output printed by the `main()` function in C++.',
    type: 'multiple_choice',
    points: 3,
    options: [
      '15 15',
      '15 35',
      '5 15',
      '5 35'
    ],
    correctOptionIndex: 0,
    explanation: '`x` is passed by reference (`int &x`), modifying `p` in-place to `5 + 10 = 15`. `y` is passed by value, so changes to `y` do not affect `q`. Output is `15 15`.',
    hint: 'The ampersand `&` indicates an alias/reference to the original caller variable.'
  },
  {
    id: 'q4',
    qNumber: 4,
    syllabusStandard: '11th',
    topic: 'C++ Functions: Default Arguments Order',
    language: 'C++',
    title: 'Question 4: Default Arguments in C++ Function Prototypes',
    codeSnippet: `#include <iostream>
using namespace std;

int calculate(int x, int y = 4, int z = 2) {
    return (x * y) - z;
}

int main() {
    cout << calculate(5, 3) << " " << calculate(6) << endl;
    return 0;
}`,
    description: 'What output is generated by calling `calculate(5, 3)` and `calculate(6)`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '13 22',
      '15 24',
      '13 24',
      '11 22'
    ],
    correctOptionIndex: 0,
    explanation: '`calculate(5, 3)` uses `x=5, y=3, z=2` default -> `(5*3)-2 = 13`. `calculate(6)` uses `x=6, y=4, z=2` defaults -> `(6*4)-2 = 22`.',
    hint: 'Missing trailing arguments are filled in from right to left using the default values.'
  },
  {
    id: 'q5',
    qNumber: 5,
    syllabusStandard: '11th',
    topic: 'C++ 2D Arrays: Memory Offset Calculation',
    language: 'C++',
    title: 'Question 5: Two-Dimensional Array Traversal',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int matrix[2][3] = {{1, 2, 3}, {4, 5, 6}};
    int sum = 0;
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 3; j++) {
            if (i == j) sum += matrix[i][j];
        }
    }
    cout << "Trace Sum = " << sum << endl;
    return 0;
}`,
    description: 'What is the value of `sum` after iterating through the 2x3 matrix where `i == j`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Trace Sum = 6',
      'Trace Sum = 7',
      'Trace Sum = 9',
      'Trace Sum = 1'
    ],
    correctOptionIndex: 0,
    explanation: 'The matching indices are `(0,0)` which has value 1, and `(1,1)` which has value 5. Therefore `sum = 1 + 5 = 6`.',
    hint: 'Check matrix[0][0] and matrix[1][1].'
  },
  {
    id: 'q6',
    qNumber: 6,
    syllabusStandard: '11th',
    topic: 'C++ Classes & Objects: Private Access Specifiers',
    language: 'C++',
    title: 'Question 6: Encapsulation and Data Member Scope',
    codeSnippet: `#include <iostream>
using namespace std;

class Student {
    int rollNo; // default access specifier
public:
    void setRoll(int r) { rollNo = r; }
    int getRoll() { return rollNo; }
};

int main() {
    Student s;
    s.setRoll(101);
    cout << s.getRoll() << endl;
    return 0;
}`,
    description: 'In C++ class definitions (TN 11th CS Chapter 14), what is the default access specifier for class members if none is specified?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'private (101 is printed correctly via public accessor)',
      'public (rollNo is directly accessible globally)',
      'protected (only derived classes can access)',
      'Compile error because rollNo cannot be accessed inside member function'
    ],
    correctOptionIndex: 0,
    explanation: 'In C++, members of a class are `private` by default. Member functions within the class (`setRoll` and `getRoll`) can freely access `rollNo`, so 101 is printed.',
    hint: 'By default, C++ class members are private, while struct members are public.'
  },
  {
    id: 'q7',
    qNumber: 7,
    syllabusStandard: '11th',
    topic: 'C++ Constructors & Destructors Execution Order',
    language: 'C++',
    title: 'Question 7: Stack Unwinding and Destructor Invocation Order',
    codeSnippet: `#include <iostream>
using namespace std;

class Tracker {
    int id;
public:
    Tracker(int n) : id(n) { cout << "C" << id; }
    ~Tracker() { cout << "D" << id; }
};

int main() {
    Tracker t1(1);
    {
        Tracker t2(2);
    }
    Tracker t3(3);
    return 0;
}`,
    description: 'What exact character sequence is displayed on stdout as objects enter and exit scope in C++?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'C1C2D2C3D3D1',
      'C1C2C3D3D2D1',
      'C1C2D2C3D1D3',
      'C1D1C2D2C3D3'
    ],
    correctOptionIndex: 0,
    explanation: '1. `t1(1)` constructs -> `C1`. 2. Inner block `t2(2)` constructs -> `C2`. 3. Inner block ends, `t2` destructs -> `D2`. 4. `t3(3)` constructs -> `C3`. 5. `main` exits, destroying `t3` -> `D3`, then `t1` -> `D1` (reverse order of creation). Output: `C1C2D2C3D3D1`.',
    hint: 'Destructors are called in reverse order of construction (LIFO) when their enclosing scope ends.'
  },
  {
    id: 'q8',
    qNumber: 8,
    syllabusStandard: '11th',
    topic: 'C++ Inheritance: Multiple Inheritance Constructor Order',
    language: 'C++',
    title: 'Question 8: Constructor Calling Order in Derived Classes',
    codeSnippet: `#include <iostream>
using namespace std;

class Alpha {
public:
    Alpha() { cout << "A"; }
};

class Beta {
public:
    Beta() { cout << "B"; }
};

class Gamma : public Beta, public Alpha {
public:
    Gamma() { cout << "G"; }
};

int main() {
    Gamma obj;
    return 0;
}`,
    description: 'According to Tamil Nadu 11th CS Chapter 16 (Inheritance), what is the constructor execution order when instantiating `Gamma`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'BAG',
      'ABG',
      'GBA',
      'GAB'
    ],
    correctOptionIndex: 0,
    explanation: 'In multiple inheritance, base class constructors execute in the order they are listed in the class derivation header (`public Beta, public Alpha`). So `Beta` runs first ("B"), then `Alpha` ("A"), then `Gamma` ("G") -> `BAG`.',
    hint: 'Constructors of base classes are invoked in the order of their declaration in the inheritance list.'
  },
  {
    id: 'q9',
    qNumber: 9,
    syllabusStandard: '11th',
    topic: 'C++ Polymorphism: Operator Overloading',
    language: 'C++',
    title: 'Question 9: Unary Operator Overloading',
    codeSnippet: `#include <iostream>
using namespace std;

class Counter {
    int count;
public:
    Counter(int c = 0) : count(c) {}
    void operator++() {
        count += 5;
    }
    void display() { cout << "Count: " << count << endl; }
};

int main() {
    Counter c(10);
    ++c;
    c.display();
    return 0;
}`,
    description: 'What will be output by calling `++c` with the overloaded prefix operator method?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Count: 15',
      'Count: 11',
      'Count: 10',
      'Compilation Error: Cannot overload ++'
    ],
    correctOptionIndex: 0,
    explanation: 'The overloaded `operator++()` increments the internal `count` by 5. Starting at 10, `10 + 5 = 15`.',
    hint: 'Look at what the operator++ function body does (`count += 5`).'
  },
  {
    id: 'q10',
    qNumber: 10,
    syllabusStandard: '11th',
    topic: 'C++ Pointers: Pointer Arithmetic & Dereferencing',
    language: 'C++',
    title: 'Question 10: Pointer Dereferencing with Arrays',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int arr[] = {10, 20, 30, 40, 50};
    int *ptr = arr;
    ptr += 2;
    cout << *ptr << " " << *(ptr + 1) << endl;
    return 0;
}`,
    description: 'What numbers are printed by `*ptr` and `*(ptr + 1)` after the pointer shift?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '30 40',
      '20 30',
      '30 50',
      '40 50'
    ],
    correctOptionIndex: 0,
    explanation: '`arr` points to element at index 0 (10). `ptr += 2` shifts the pointer to index 2 (30). `*ptr` is 30, and `*(ptr + 1)` is index 3 (40).',
    hint: 'Pointer addition moves through array elements in steps of the data type size.'
  },
  {
    id: 'q11',
    qNumber: 11,
    syllabusStandard: '11th',
    topic: 'C++ Strings: Built-in C-String Functions',
    language: 'C++',
    title: 'Question 11: String Concatenation & Length in C-Strings',
    codeSnippet: `#include <iostream>
#include <cstring>
using namespace std;

int main() {
    char str1[20] = "Tamil";
    char str2[] = "Nadu";
    strcat(str1, str2);
    cout << strlen(str1) << " " << str1 << endl;
    return 0;
}`,
    description: 'What does `strlen(str1)` return after `strcat(str1, str2)` operates on the strings?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '9 TamilNadu',
      '10 TamilNadu',
      '20 TamilNadu',
      '5 Tamil'
    ],
    correctOptionIndex: 0,
    explanation: '`strcat` appends "Nadu" to "Tamil", resulting in "TamilNadu". `strlen("TamilNadu")` is 5 + 4 = 9 characters (excluding null terminator `\\0`).',
    hint: 'strlen counts the number of characters before the null terminator.'
  },
  {
    id: 'q12',
    qNumber: 12,
    syllabusStandard: '11th',
    topic: 'C++ Recursion: Factorial Base Case Execution',
    language: 'C++',
    title: 'Question 12: Recursive Function Call Stack',
    codeSnippet: `#include <iostream>
using namespace std;

int fun(int n) {
    if (n <= 1) return 1;
    return n + fun(n - 2);
}

int main() {
    cout << fun(6) << endl;
    return 0;
}`,
    description: 'Compute the return value of `fun(6)` following the recursive evaluation path.',
    type: 'multiple_choice',
    points: 3,
    options: [
      '13',
      '12',
      '15',
      '6'
    ],
    correctOptionIndex: 0,
    explanation: '`fun(6) = 6 + fun(4) = 6 + (4 + fun(2)) = 6 + 4 + (2 + fun(0)) = 6 + 4 + 2 + 1 = 13` (since `fun(0)` hits base case `n <= 1` returning 1).',
    hint: 'Trace the stack: fun(6) -> 6 + fun(4) -> 4 + fun(2) -> 2 + fun(0).'
  },

  // ==================== 12TH STANDARD TN STATE BOARD CS (PYTHON, DBMS & INTEGRATION) ====================
  {
    id: 'q13',
    qNumber: 13,
    syllabusStandard: '12th',
    topic: 'Python Control Structures: Range Step Argument',
    language: 'Python',
    title: 'Question 13: Reverse Step Iteration in Python `range()`',
    codeSnippet: `total = 0
for i in range(10, 0, -3):
    total += i
print("Total =", total)`,
    description: 'In Tamil Nadu 12th CS Chapter 6 (Control Structures), what value is calculated by the loop iterating with step `-3`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Total = 22',
      'Total = 19',
      'Total = 25',
      'Total = 15'
    ],
    correctOptionIndex: 0,
    explanation: 'The loop produces values 10, 7, 4, 1 (since stop is 0, non-inclusive). `10 + 7 + 4 + 1 = 22`.',
    hint: 'Start at 10, subtract 3 each step until > 0: 10, 7, 4, 1.'
  },
  {
    id: 'q14',
    qNumber: 14,
    syllabusStandard: '12th',
    topic: 'Python Strings: Negative Step Slicing',
    language: 'Python',
    title: 'Question 14: String Slicing with Steps & Boundaries',
    codeSnippet: `text = "TAMILNADU"
slice1 = text[1:7:2]
slice2 = text[::-2]
print(slice1, slice2)`,
    description: 'What two sliced strings are printed by Python string indexing?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'AIN UAMAT',
      'AML UDNL',
      'AIN UDAMA',
      'AML UAMAT'
    ],
    correctOptionIndex: 0,
    explanation: '`text[1:7:2]`: indices 1 ("A"), 3 ("I"), 5 ("N") -> "AIN". `text[::-2]`: backwards from index 8 ("U"), 6 ("A"), 4 ("M"), 2 ("A"), 0 ("T") -> "UAMAT".',
    hint: 'Slice syntax is [start:stop:step]. Step 2 skips every second letter.'
  },
  {
    id: 'q15',
    qNumber: 15,
    syllabusStandard: '12th',
    topic: 'Python Lists: List Comprehension with Filter',
    language: 'Python',
    title: 'Question 15: List Comprehension and In-Place Aliasing',
    codeSnippet: `nums = [1, 2, 3, 4, 5, 6]
evens_squared = [x**2 for x in nums if x % 2 == 0]
print(evens_squared)`,
    description: 'What is the output of the list comprehension filtering even numbers and squaring them?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '[4, 16, 36]',
      '[1, 9, 25]',
      '[2, 4, 6]',
      '[4, 8, 12]'
    ],
    correctOptionIndex: 0,
    explanation: 'Even numbers in `nums` are 2, 4, 6. Squaring them yields `2**2=4, 4**2=16, 6**2=36` -> `[4, 16, 36]`.',
    hint: 'Only even numbers (2, 4, 6) satisfy x % 2 == 0.'
  },
  {
    id: 'q16',
    qNumber: 16,
    syllabusStandard: '12th',
    topic: 'Python Tuples & Sets: Immutability and Set Operations',
    language: 'Python',
    title: 'Question 16: Set Symmetric Difference and Set Operations',
    codeSnippet: `set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}
sym_diff = set_a ^ set_b
print(sorted(list(sym_diff)))`,
    description: 'According to Tamil Nadu 12th CS Chapter 9 (Lists, Tuples, Sets and Dictionaries), what is the result of the symmetric difference operator `^`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '[1, 2, 5, 6]',
      '[3, 4]',
      '[1, 2, 3, 4, 5, 6]',
      '[1, 2]'
    ],
    correctOptionIndex: 0,
    explanation: 'Symmetric difference (`^`) returns elements in either set_a or set_b, but NOT in both (i.e. `(A ∪ B) - (A ∩ B)`). Common elements 3, 4 are excluded, leaving `{1, 2, 5, 6}`.',
    hint: 'Symmetric difference means elements in either set, but not in both.'
  },
  {
    id: 'q17',
    qNumber: 17,
    syllabusStandard: '12th',
    topic: 'Python Dictionaries: Keys, Values & `.get()` Default',
    language: 'Python',
    title: 'Question 17: Dictionary Lookup with Fallback Defaults',
    codeSnippet: `marks = {"CS": 98, "Maths": 95, "Physics": 92}
val1 = marks.get("Chemistry", 85)
val2 = marks.get("CS", 100)
print(val1 + val2)`,
    description: 'What sum is returned by invoking `.get()` with key defaults?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '183',
      '198',
      '180',
      'KeyError: Chemistry not found'
    ],
    correctOptionIndex: 0,
    explanation: '"Chemistry" does not exist in `marks`, so `.get("Chemistry", 85)` returns the default 85. "CS" exists with value 98, so `.get("CS", 100)` returns 98. `85 + 98 = 183`.',
    hint: 'dict.get(key, default) returns the key value if found, else default without raising KeyError.'
  },
  {
    id: 'q18',
    qNumber: 18,
    syllabusStandard: '12th',
    topic: 'Python OOP: Class Variables vs Instance Variables',
    language: 'Python',
    title: 'Question 18: Class Attribute Mutation via Instance',
    codeSnippet: `class School:
    board = "TN State Board"
    def __init__(self, name):
        self.name = name

s1 = School("Chennai School")
s2 = School("Madurai School")
School.board = "TN SCERT Board"
s1.board = "Custom Board"

print(s1.board, s2.board)`,
    description: 'In Python OOP (TN 12th CS Chapter 10), how does instance attribute shadowing interact with class variables?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Custom Board TN SCERT Board',
      'TN SCERT Board TN SCERT Board',
      'Custom Board Custom Board',
      'TN State Board TN SCERT Board'
    ],
    correctOptionIndex: 0,
    explanation: '`s1.board = "Custom Board"` creates an instance attribute on `s1`, shadowing the class variable. `s2.board` still accesses the mutated class variable `School.board = "TN SCERT Board"`.',
    hint: 'Setting an attribute on an instance creates an instance-level attribute without changing other instances.'
  },
  {
    id: 'q19',
    qNumber: 19,
    syllabusStandard: '12th',
    topic: 'Python Variable Scope: Global & Nonlocal Keywords',
    language: 'Python',
    title: 'Question 19: Global Variable Scope Modification',
    codeSnippet: `count = 10

def increment():
    global count
    count += 5

def local_test():
    count = 50

increment()
local_test()
print("Final Count =", count)`,
    description: 'What is the final value of the global `count` variable after both functions execute?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Final Count = 15',
      'Final Count = 50',
      'Final Count = 10',
      'Final Count = 65'
    ],
    correctOptionIndex: 0,
    explanation: '`increment()` uses `global count` to update the global count to 15. `local_test()` assigns to a local variable `count = 50` which does not affect the global count.',
    hint: 'The global keyword binds the assignment to the module-level variable.'
  },
  {
    id: 'q20',
    qNumber: 20,
    syllabusStandard: '12th',
    topic: 'Python CSV Module: DictReader Delimiters',
    language: 'Python',
    title: 'Question 20: Processing CSV Files with Python `csv` Module',
    codeSnippet: `import csv
# Suppose data.csv contains:
# Roll,Name,Marks
# 101,Anitha,96
# 102,Bala,89

total = 0
# Code snippet logic:
rows = [{"Roll": "101", "Marks": "96"}, {"Roll": "102", "Marks": "89"}]
for r in rows:
    total += int(r["Marks"])
print("Average =", total / len(rows))`,
    description: 'In Tamil Nadu 12th CS Chapter 13 (Python and CSV Files), what average mark is computed from the CSV rows?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Average = 92.5',
      'Average = 93.0',
      'Average = 92.0',
      'TypeError: cannot convert str to int'
    ],
    correctOptionIndex: 0,
    explanation: '`(96 + 89) = 185`. `185 / 2 = 92.5`.',
    hint: 'Remember that CSV reader values are read as strings and must be cast with int().'
  },
  {
    id: 'q21',
    qNumber: 21,
    syllabusStandard: '12th',
    topic: 'DBMS: Relational SQL Queries & Aggregate Functions',
    language: 'SQL',
    title: 'Question 21: SQL GROUP BY with HAVING Filter',
    codeSnippet: `-- Schema: STUDENTS (RollNo, Dept, Marks)
SELECT Dept, AVG(Marks) AS AvgMarks
FROM STUDENTS
GROUP BY Dept
HAVING COUNT(*) >= 2;`,
    description: 'In Tamil Nadu 12th CS Chapter 12 (Structured Query Language), what does the `HAVING` clause filter?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Groups of departments that have 2 or more students',
      'Individual student rows before grouping',
      'Only departments whose average mark is greater than 2',
      'Syntax error: HAVING cannot be used with COUNT(*)'
    ],
    correctOptionIndex: 0,
    explanation: '`WHERE` filters individual rows before grouping, while `HAVING` filters aggregated group records. `HAVING COUNT(*) >= 2` restricts output to departments having 2 or more student records.',
    hint: 'HAVING is used to filter groups created by the GROUP BY clause.'
  },
  {
    id: 'q22',
    qNumber: 22,
    syllabusStandard: '12th',
    topic: 'DBMS SQL: String Pattern Matching with LIKE',
    language: 'SQL',
    title: 'Question 22: SQL Wildcard Characters `%` and `_`',
    codeSnippet: `-- Find student names
SELECT StudentName
FROM STUDENTS
WHERE StudentName LIKE 'K__a%';`,
    description: 'Which of the following student names will match the pattern `\'K__a%\'` (where `_` is a single char wildcard and `%` matches zero or more chars)?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Kavya (Starts with K, 2 chars "av", followed by "a", then "ya")',
      'Kala (Only 1 char between K and l)',
      'Kumar (Does not have "a" at the 4th position)',
      'K (Too short)'
    ],
    correctOptionIndex: 0,
    explanation: '`K__a%` requires: 1st char = \'K\', 2nd & 3rd chars = any 2 characters (`__`), 4th char = \'a\', followed by any number of characters (`%`). In "Kavya": K(1), a(2), v(3), a(4), ya(5-6) -> MATCHES.',
    hint: 'Underscore `_` represents exactly one character; percent `%` represents zero or more characters.'
  },
  {
    id: 'q23',
    qNumber: 23,
    syllabusStandard: '12th',
    topic: 'Python SQLite3 / Database Connection API',
    language: 'Python',
    title: 'Question 23: Python SQLite Database Query Fetching',
    codeSnippet: `import sqlite3
# Assuming connection 'conn' and cursor 'cur':
# Table has 5 student records
# cur.execute("SELECT * FROM Student WHERE Marks > 80")
# 3 students qualify.
# res = cur.fetchmany(2)
# print(len(res))`,
    description: 'In Tamil Nadu 12th CS Chapter 15 (Data Manipulation through SQL), what is returned by `cur.fetchmany(2)` when 3 records qualify?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'A list containing exactly 2 record tuples',
      'A list containing all 3 record tuples',
      'An integer count 2',
      'A single record tuple'
    ],
    correctOptionIndex: 0,
    explanation: '`fetchmany(size)` fetches the next set of rows of a query result, returning a list of tuples up to `size` (here 2).',
    hint: 'fetchmany(size) limits the returned records to the requested number.'
  },
  {
    id: 'q24',
    qNumber: 24,
    syllabusStandard: '12th',
    topic: 'Python & C++ Integration (MinGW / System Call)',
    language: 'Python',
    title: 'Question 24: Executing C++ Executables from Python Scripts',
    codeSnippet: `import os, sys
# Chapter 15: Integrating C++ with Python
# Command to compile C++ program 'prog.cpp' using g++:
cmd = "g++ prog.cpp -o prog.exe"
status = os.system(cmd)
# If compilation succeeds:
print("Exit Status =", status)`,
    description: 'In TN 12th CS Chapter 15 (Importing C++ Programs in Python), what integer exit status is returned by `os.system()` when compilation succeeds without errors?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Exit Status = 0',
      'Exit Status = 1',
      'Exit Status = -1',
      'Exit Status = 200'
    ],
    correctOptionIndex: 0,
    explanation: 'In operating systems and POSIX/Windows CLI tools, an exit status of 0 represents successful execution with zero errors.',
    hint: 'In shell systems, 0 indicates success, non-zero indicates an error.'
  },

  // ==================== QUESTION 25: PROMPT TYPE (BUILD A WEBSITE) ====================
  {
    id: 'q25',
    qNumber: 25,
    syllabusStandard: 'WebDev',
    topic: 'Modern Web Development: HTML5, Tailwind/CSS & JavaScript Interactive Application',
    language: 'HTML/CSS/JS',
    title: 'Question 25: Build a website on your favourite theme. Give me your prompt',
    description: `🚀 **Website Builder Challenge**: Build a website on your favourite theme. Give me your prompt.

Type your detailed prompt into the typebox below. Describe your chosen theme, UI design, components, color scheme, interactive behaviors, and features. You can also build and preview the corresponding web code in the interactive sandbox below!`,
    type: 'website_prompt',
    points: 28,
    websiteTemplate: {
      html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Favorite Theme Website</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 font-sans p-6 min-h-screen flex items-center justify-center">
  <div class="max-w-2xl w-full bg-slate-900 border border-cyan-500/30 rounded-3xl p-8 shadow-2xl text-center space-y-4">
    <div class="w-16 h-16 rounded-2xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center mx-auto text-3xl font-bold">
      ✨
    </div>
    <h1 class="text-3xl font-black text-white font-orbitron">My Favourite Theme Website</h1>
    <p class="text-slate-400 text-sm">Enter your prompt in the typebox above to describe and build your custom website.</p>
  </div>
</body>
</html>`,
      css: `/* Custom CSS Enhancements */
body {
  font-family: system-ui, -apple-system, sans-serif;
}`,
      js: `console.log("Website initialized.");`
    },
    hint: 'Give your detailed prompt describing your favorite theme, components, user interactions, and visual styling.'
  }
];

// Pre-populated Attended Tamil Nadu 12th Computer Science Candidates
export const INITIAL_CANDIDATE_SUBMISSIONS: CandidateSubmission[] = [
  {
    id: 'cand-tn-001',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Natish R',
      email: 'natish1349@gmail.com',
      phone: '9943404409',
      role: '12th Computer Science Scholar',
      schoolName: 'Tamil Nadu Higher Secondary School, Chennai',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'A modern cyber-security learning portal for high school students in Tamil Nadu, featuring interactive terminal quizzes and threat defense simulations.',
        htmlCode: '<div class="p-8 text-center bg-slate-900 text-white rounded-3xl"><h1 class="text-3xl font-bold text-cyan-400">CyberShield TN</h1><p class="text-slate-300 mt-2">Interactive Cyber Defense Learning Engine</p></div>',
        cssCode: 'body { background: #020617; font-family: sans-serif; }',
        jsCode: 'console.log("CyberShield TN Loaded");'
      }
    ],
    startedAt: '2026-08-25T08:30:00.000Z',
    submittedAt: '2026-08-25T09:18:14.000Z',
    timeSpentSeconds: 2894,
    evaluation: {
      mcqScore: 72,
      websitePromptDesign: 14,
      websitePromptFunctionality: 14,
      totalScore: 100,
      grade: 'A+',
      badge: 'State Rank 1 Gold',
      feedback: 'Flawless performance across all 24 C++, Python, and SQL State Board MCQs with an outstanding cyber defense web portal prompt.',
      evaluatedAt: '2026-08-25T09:20:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-002',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Priya Sundaram',
      email: 'priya.sundaram@vidyamandir.edu.in',
      phone: '9840123456',
      role: '12th Computer Science',
      schoolName: 'Vidya Mandir Senior Secondary School, Mylapore, Chennai',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 1 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu Smart Agriculture Portal connecting farmers with direct weather alerts, market prices, and soil telemetry visualizers.',
        htmlCode: '<div class="p-6 bg-emerald-950 text-white rounded-2xl text-center"><h1 class="text-2xl font-bold text-emerald-400">Uzhavan Smart AgTech</h1></div>'
      }
    ],
    startedAt: '2026-08-25T08:45:00.000Z',
    submittedAt: '2026-08-25T09:32:00.000Z',
    timeSpentSeconds: 2820,
    evaluation: {
      mcqScore: 69,
      websitePromptDesign: 15,
      websitePromptFunctionality: 14,
      totalScore: 98,
      grade: 'A+',
      badge: 'State Rank 2 Silver',
      feedback: 'Excellent algorithmic reasoning and well-structured Agricultural Technology portal architecture.',
      evaluatedAt: '2026-08-25T09:35:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-003',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Kavin Kumar S',
      email: 'kavinkumar.tvs@gmail.com',
      phone: '9443219870',
      role: '12th Computer Science',
      schoolName: 'TVS Higher Secondary School, Madurai',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 1 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Interactive Chandrayaan & Space Exploration live 3D orbital trajectory simulation and educational mission tracker.',
        htmlCode: '<div class="p-8 bg-indigo-950 text-white rounded-3xl"><h1 class="text-3xl font-bold text-indigo-400">ISRO Deep Space Hub</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:00:00.000Z',
    submittedAt: '2026-08-25T09:47:00.000Z',
    timeSpentSeconds: 2820,
    evaluation: {
      mcqScore: 69,
      websitePromptDesign: 14,
      websitePromptFunctionality: 13,
      totalScore: 96,
      grade: 'A+',
      badge: 'State Rank 3 Bronze',
      feedback: 'Outstanding mastery of Python data structures and SQL relational database queries.',
      evaluatedAt: '2026-08-25T09:50:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-004',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Ananya Raman',
      email: 'ananya.raman@psbb.ac.in',
      phone: '9791054321',
      role: '12th Computer Science',
      schoolName: 'PSBB Millennium School, Chennai',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu Heritage & Digital Palm Leaf Manuscript Archive with high-resolution viewer and Tamil phonetic search.',
        htmlCode: '<div class="p-8 bg-amber-950 text-white rounded-3xl"><h1 class="text-3xl font-bold text-amber-400">Tamil Classical Digital Archive</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:10:00.000Z',
    submittedAt: '2026-08-25T09:54:00.000Z',
    timeSpentSeconds: 2640,
    evaluation: {
      mcqScore: 72,
      websitePromptDesign: 13,
      websitePromptFunctionality: 10,
      totalScore: 95,
      grade: 'A+',
      badge: 'State Top 5 Honors',
      feedback: 'Perfect MCQ marks and creative Tamil cultural web preservation application.',
      evaluatedAt: '2026-08-25T09:58:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-005',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Dhanush Karthik',
      email: 'dhanush.karthik@stjoseph.edu.in',
      phone: '9842187654',
      role: '12th Computer Science',
      schoolName: "St. Joseph's Higher Secondary School, Trichy",
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 1 },
      {
        questionId: 'q25',
        websitePrompt: 'Autonomous Emergency Hospital Bed & Blood Donor Real-time Matching System across Tamil Nadu districts.',
        htmlCode: '<div class="p-6 bg-red-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-red-400">TN Emergency Medical Grid</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:15:00.000Z',
    submittedAt: '2026-08-25T10:02:00.000Z',
    timeSpentSeconds: 2820,
    evaluation: {
      mcqScore: 69,
      websitePromptDesign: 13,
      websitePromptFunctionality: 12,
      totalScore: 94,
      grade: 'A+',
      badge: 'State Top 10 Honors',
      feedback: 'Very solid comprehension of OOP in C++ and SQLite operations.',
      evaluatedAt: '2026-08-25T10:05:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-006',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Swetha Murali',
      email: 'swetha.m@cluny.edu.in',
      phone: '9629143890',
      role: '12th Computer Science',
      schoolName: 'Cluny Convent Higher Secondary School, Salem',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 1 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Digital Examination & Public Exam Revision Tracker for 10th and 12th State Board syllabus.',
        htmlCode: '<div class="p-6 bg-purple-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-purple-400">TN Pariksha Portal</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:20:00.000Z',
    submittedAt: '2026-08-25T10:05:00.000Z',
    timeSpentSeconds: 2700,
    evaluation: {
      mcqScore: 69,
      websitePromptDesign: 12,
      websitePromptFunctionality: 11,
      totalScore: 92,
      grade: 'A',
      badge: 'State CS Distinction',
      feedback: 'Consistent score with great clarity in SQL syntax and Python file I/O operations.',
      evaluatedAt: '2026-08-25T10:10:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-007',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Vignesh Balaji',
      email: 'vignesh.balaji@coimbatoremodel.edu.in',
      phone: '9843056789',
      role: '12th Computer Science',
      schoolName: 'Government Model Higher Secondary School, Coimbatore',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu Renewable Solar Grid monitoring dashboard for high schools.',
        htmlCode: '<div class="p-6 bg-yellow-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-yellow-400">SolarTN High School Grid</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:30:00.000Z',
    submittedAt: '2026-08-25T10:15:00.000Z',
    timeSpentSeconds: 2700,
    evaluation: {
      mcqScore: 72,
      websitePromptDesign: 10,
      websitePromptFunctionality: 8,
      totalScore: 90,
      grade: 'A',
      badge: 'State CS Distinction',
      feedback: 'Full marks in MCQs; website prompt covers clean solar monitoring metrics.',
      evaluatedAt: '2026-08-25T10:20:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-008',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Deepika Thangaraj',
      email: 'deepika.thangaraj@srvboys.edu.in',
      phone: '9443598712',
      role: '12th Computer Science',
      schoolName: 'SRV Boys Higher Secondary School, Rasipuram',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 1 },
      { questionId: 'q24', selectedOptionIndex: 1 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu State Board Computer Science Algorithm Visualizer (Bubble Sort, Linear Search, Binary Search).',
        htmlCode: '<div class="p-6 bg-cyan-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-cyan-400">TN AlgoLab Interactive</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:40:00.000Z',
    submittedAt: '2026-08-25T10:28:00.000Z',
    timeSpentSeconds: 2880,
    evaluation: {
      mcqScore: 66,
      websitePromptDesign: 12,
      websitePromptFunctionality: 10,
      totalScore: 88,
      grade: 'B+',
      badge: 'State CS Certified',
      feedback: 'Very good conceptual knowledge on control flow, loops, and CSV processing.',
      evaluatedAt: '2026-08-25T10:30:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-009',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Rahul Sundaram',
      email: 'rahul.sundaram@davchennai.edu.in',
      phone: '9840987650',
      role: '12th Computer Science',
      schoolName: 'DAV Boys Senior Secondary School, Gopalapuram, Chennai',
      standard: '12th Computer Science'
    },
    status: 'evaluated',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 1 },
      { questionId: 'q23', selectedOptionIndex: 1 },
      { questionId: 'q24', selectedOptionIndex: 1 },
      {
        questionId: 'q25',
        websitePrompt: 'High School Code Runner & Sandbox for C++ and Python syntax verification.',
        htmlCode: '<div class="p-6 bg-slate-900 text-white rounded-2xl"><h1 class="text-2xl font-bold text-sky-400">TN CodeSandbox</h1></div>'
      }
    ],
    startedAt: '2026-08-25T09:45:00.000Z',
    submittedAt: '2026-08-25T10:33:00.000Z',
    timeSpentSeconds: 2880,
    evaluation: {
      mcqScore: 63,
      websitePromptDesign: 12,
      websitePromptFunctionality: 10,
      totalScore: 85,
      grade: 'B+',
      badge: 'State CS Certified',
      feedback: 'Good problem solving skills with solid Python function scoping understanding.',
      evaluatedAt: '2026-08-25T10:35:00.000Z',
      evaluatedBy: 'State Board Technical Evaluator',
      isPublishedToLeaderboard: true
    }
  },
  {
    id: 'cand-tn-010',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Harini Velu',
      email: 'harini.velu@stbedes.edu.in',
      phone: '9884102938',
      role: '12th Computer Science',
      schoolName: "St. Bede's Anglo Indian HSS, Santhome, Chennai",
      standard: '12th Computer Science'
    },
    status: 'submitted',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu Smart Public Library book search and digital catalogue with reservation alerts.',
        htmlCode: '<div class="p-6 bg-teal-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-teal-400">Connemara e-Library Portal</h1></div>'
      }
    ],
    startedAt: '2026-08-25T10:00:00.000Z',
    submittedAt: '2026-08-25T10:48:00.000Z',
    timeSpentSeconds: 2880
  },
  {
    id: 'cand-tn-011',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Saravanan P',
      email: 'saravanan.p@chennaigirls.edu.in',
      phone: '9789012345',
      role: '12th Computer Science',
      schoolName: 'Govt Higher Secondary School, Ashok Nagar, Chennai',
      standard: '12th Computer Science'
    },
    status: 'submitted',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 },
      { questionId: 'q16', selectedOptionIndex: 0 },
      { questionId: 'q17', selectedOptionIndex: 0 },
      { questionId: 'q18', selectedOptionIndex: 0 },
      { questionId: 'q19', selectedOptionIndex: 0 },
      { questionId: 'q20', selectedOptionIndex: 0 },
      { questionId: 'q21', selectedOptionIndex: 0 },
      { questionId: 'q22', selectedOptionIndex: 0 },
      { questionId: 'q23', selectedOptionIndex: 0 },
      { questionId: 'q24', selectedOptionIndex: 0 },
      {
        questionId: 'q25',
        websitePrompt: 'Tamil Nadu Heritage Temple Architecture and Chola Bronze Sculptures Virtual Tour.',
        htmlCode: '<div class="p-6 bg-amber-950 text-white rounded-2xl"><h1 class="text-2xl font-bold text-amber-400">Thanjavur Brihadisvara 3D Tour</h1></div>'
      }
    ],
    startedAt: '2026-08-25T10:10:00.000Z',
    submittedAt: '2026-08-25T10:55:00.000Z',
    timeSpentSeconds: 2700
  },
  {
    id: 'cand-tn-012',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Keerthana M',
      email: 'keerthana.m@montfort.edu.in',
      phone: '9444019283',
      role: '12th Computer Science',
      schoolName: 'Montfort Anglo Indian Higher Secondary School, Yercaud',
      standard: '12th Computer Science'
    },
    status: 'in_progress',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 },
      { questionId: 'q9', selectedOptionIndex: 0 },
      { questionId: 'q10', selectedOptionIndex: 0 },
      { questionId: 'q11', selectedOptionIndex: 0 },
      { questionId: 'q12', selectedOptionIndex: 0 },
      { questionId: 'q13', selectedOptionIndex: 0 },
      { questionId: 'q14', selectedOptionIndex: 0 },
      { questionId: 'q15', selectedOptionIndex: 0 }
    ],
    startedAt: '2026-08-25T10:30:00.000Z',
    timeSpentSeconds: 1540
  },
  {
    id: 'cand-tn-013',
    candidateCode: 'CANDIDATE-2025',
    details: {
      fullName: 'Sanjay Ram',
      email: 'sanjay.ram@donbosco.edu.in',
      phone: '9840512340',
      role: '12th Computer Science',
      schoolName: 'Don Bosco Matriculation HSS, Egmore, Chennai',
      standard: '12th Computer Science'
    },
    status: 'in_progress',
    answers: [
      { questionId: 'q1', selectedOptionIndex: 0 },
      { questionId: 'q2', selectedOptionIndex: 0 },
      { questionId: 'q3', selectedOptionIndex: 0 },
      { questionId: 'q4', selectedOptionIndex: 0 },
      { questionId: 'q5', selectedOptionIndex: 0 },
      { questionId: 'q6', selectedOptionIndex: 0 },
      { questionId: 'q7', selectedOptionIndex: 0 },
      { questionId: 'q8', selectedOptionIndex: 0 }
    ],
    startedAt: '2026-08-25T10:35:00.000Z',
    timeSpentSeconds: 960
  }
];

/**
 * Generates a full cohort of up to 100 realistic candidate submissions
 * across various Tamil Nadu schools, scores, and assessment statuses.
 */
export function generateCohortCandidates(targetCount: number = 100): CandidateSubmission[] {
  const tnSchools = [
    'Tamil Nadu Higher Secondary School, Chennai',
    'Vidya Mandir Senior Secondary School, Mylapore, Chennai',
    'TVS Higher Secondary School, Madurai',
    'PSBB Millennium School, Chennai',
    "St. Joseph's Higher Secondary School, Trichy",
    'Cluny Convent Higher Secondary School, Salem',
    'Government Model Higher Secondary School, Coimbatore',
    'SRV Boys Higher Secondary School, Rasipuram',
    'DAV Boys Senior Secondary School, Gopalapuram, Chennai',
    "St. Bede's Anglo Indian HSS, Santhome, Chennai",
    'Govt Higher Secondary School, Ashok Nagar, Chennai',
    'Montfort Anglo Indian Higher Secondary School, Yercaud',
    'Don Bosco Matriculation HSS, Egmore, Chennai',
    'SBOA School & Junior College, Anna Nagar, Chennai',
    'Lady Andal Venkatasubba Rao School, Chetpet, Chennai',
    'Chinmaya Vidyalaya Higher Secondary School, Taylors Road',
    'Bala Vidya Mandir Senior Secondary School, Adyar, Chennai',
    'St. Xavier Higher Secondary School, Palayamkottai, Tirunelveli',
    'Kendriya Vidyalaya CLRI, Adyar, Chennai',
    'Padma Seshadri Bala Bhavan Senior Secondary School, Nungambakkam'
  ];

  const firstNames = [
    'Aarav', 'Abhinav', 'Aditi', 'Ajay', 'Akash', 'Amrita', 'Anand', 'Ananya', 'Anirudh', 'Anjali',
    'Aravind', 'Archana', 'Arjun', 'Ashwin', 'Balaji', 'Bhavani', 'Chandran', 'Deepa', 'Deepak', 'Deepika',
    'Dhanush', 'Divya', 'Ganesh', 'Gautham', 'Geetha', 'Gokul', 'Harini', 'Harish', 'Janani', 'Karthik',
    'Kavitha', 'Kavin', 'Keerthana', 'Kishore', 'Krishnan', 'Lakshmi', 'Madhavan', 'Manoj', 'Meena', 'Mithun',
    'Muralidharan', 'Nandhini', 'Naresh', 'Naveen', 'Nithya', 'Nivedha', 'Pavithra', 'Pooja', 'Pranav', 'Prasad',
    'Prashanth', 'Priya', 'Priyanka', 'Raghav', 'Rahul', 'Rajesh', 'Rakesh', 'Ramachandran', 'Ramesh', 'Ranjith',
    'Rithika', 'Rohan', 'Rohit', 'Sahana', 'Sai', 'Sakthi', 'Samriddhi', 'Sanjay', 'Saravanan', 'Sasikumar',
    'Sathish', 'Selvam', 'Shalini', 'Shankar', 'Shreya', 'Shruthi', 'Siddharth', 'Sindhu', 'Sneha', 'Soundarya',
    'Sowmya', 'Srikanth', 'Srinivasan', 'Subhash', 'Sudha', 'Sujatha', 'Suresh', 'Swaminathan', 'Swetha', 'Tamilarasan',
    'Tanvi', 'Tarun', 'Thangavel', 'Udhaya', 'Vaishnavi', 'Varun', 'Vasanth', 'Vignesh', 'Vijay', 'Vishnu'
  ];

  const lastInitials = ['A', 'B', 'C', 'D', 'G', 'K', 'M', 'N', 'P', 'R', 'S', 'T', 'V'];

  const results: CandidateSubmission[] = [...INITIAL_CANDIDATE_SUBMISSIONS];
  const existingEmails = new Set(results.map((c) => c.details.email.toLowerCase()));

  let index = results.length + 1;
  while (results.length < targetCount && index <= 200) {
    const fName = firstNames[(index * 7) % firstNames.length];
    const initial = lastInitials[(index * 11) % lastInitials.length];
    const fullName = `${fName} ${initial}`;
    const email = `${fName.toLowerCase()}.${initial.toLowerCase()}${index}@tnschools.edu.in`;
    const school = tnSchools[index % tnSchools.length];
    const phone = `9840${String(100000 + index * 37).slice(-6)}`;

    if (existingEmails.has(email)) {
      index++;
      continue;
    }
    existingEmails.add(email);

    // Compute realistic score distribution (70% Evaluated with 75-99 marks, 15% Submitted, 15% In-Progress)
    const isEvaluated = index <= targetCount * 0.75;
    const isSubmitted = !isEvaluated && index <= targetCount * 0.90;
    const status: AssessmentStatus = isEvaluated ? 'evaluated' : isSubmitted ? 'submitted' : 'in_progress';

    const correctCount = Math.max(16, Math.min(24, 24 - (index % 7)));
    const answers: CandidateAnswer[] = [];
    for (let q = 0; q < 24; q++) {
      const qId = `q${q + 1}`;
      const isCorrect = q < correctCount;
      answers.push({
        questionId: qId,
        selectedOptionIndex: isCorrect ? 0 : 1
      });
    }

    answers.push({
      questionId: 'q25',
      websitePrompt: `Interactive Tamil Nadu 12th Computer Science Web Application #${index} with responsive UI.`,
      htmlCode: `<div class="p-6 bg-slate-900 text-white rounded-2xl text-center"><h2 class="text-xl font-bold text-cyan-400">TN Tech Project #${index}</h2></div>`
    });

    const mcqScore = correctCount * 3;
    const designScore = 12 + (index % 4);
    const funcScore = 11 + (index % 4);
    const totalScore = Math.min(100, mcqScore + designScore + funcScore);
    const grade = totalScore >= 95 ? 'A+' : totalScore >= 90 ? 'A' : totalScore >= 80 ? 'B+' : 'B';

    const candidate: CandidateSubmission = {
      id: `cand-tn-${String(index).padStart(3, '0')}`,
      candidateCode: 'CANDIDATE-2025',
      details: {
        fullName,
        email,
        phone,
        role: '12th Computer Science',
        schoolName: school,
        standard: '12th Computer Science'
      },
      status,
      answers,
      startedAt: new Date(Date.now() - (index * 180000)).toISOString(),
      submittedAt: status !== 'in_progress' ? new Date(Date.now() - (index * 120000)).toISOString() : undefined,
      timeSpentSeconds: 1800 + (index * 17) % 1100,
      evaluation: isEvaluated ? {
        mcqScore,
        websitePromptDesign: designScore,
        websitePromptFunctionality: funcScore,
        totalScore,
        grade,
        badge: totalScore >= 95 ? 'State Rank Gold' : totalScore >= 90 ? 'State CS Honors' : 'State CS Certified',
        feedback: `Candidate demonstrated solid mastery in ${school}. Scored ${totalScore}/100.`,
        evaluatedAt: new Date(Date.now() - (index * 90000)).toISOString(),
        evaluatedBy: 'State Board Technical Evaluator',
        isPublishedToLeaderboard: true
      } : undefined
    };

    results.push(candidate);
    index++;
  }

  return results;
}

export const INITIAL_EMAIL_NOTIFICATIONS: EmailNotification[] = [];


