import { Question, CandidateSubmission, EmailNotification } from '../types';

export const CREATOR_ACCESS_CODE = 'I_Love_Honey';
export const CANDIDATE_ACCESS_CODE = '#B3L2H100%';

export const DEFAULT_QUESTIONS: Question[] = [
  // ==================== 11TH STANDARD TN STATE BOARD CS (C++ & CORE CONCEPTS) ====================
  {
    id: 'q1',
    qNumber: 1,
    syllabusStandard: '11th',
    topic: 'C++ Tokens, Operators & Precedence',
    language: 'C++',
    title: 'Question 1: C++ Prefix & Postfix Increment Operators',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int a = 5, b = 10, c;
    c = ++a * b--;
    cout << "a = " << a << ", b = " << b << ", c = " << c << endl;
    return 0;
}`,
    description: 'Analyze the C++ code snippet above according to standard operator precedence and side effects. What will be printed on the standard output console?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'a = 6, b = 9, c = 60',
      'a = 5, b = 10, c = 50',
      'a = 6, b = 9, c = 54',
      'a = 6, b = 10, c = 60'
    ],
    correctOptionIndex: 0,
    explanation: '`++a` pre-increments `a` from 5 to 6 first. Then `6 * 10 = 60` is assigned to `c`. Finally, postfix `b--` decrements `b` from 10 to 9.',
    hint: 'Remember: prefix ++ happens before multiplication, postfix -- happens after the evaluation of the expression.'
  },
  {
    id: 'q2',
    qNumber: 2,
    syllabusStandard: '11th',
    topic: 'C++ Control Structures: Switch-Case Fallthrough',
    language: 'C++',
    title: 'Question 2: Switch-Case without Break Statements',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int val = 2, sum = 0;
    switch (val) {
        case 1: sum += 10;
        case 2: sum += 20;
        case 3: sum += 30;
        default: sum += 5;
    }
    cout << "Sum = " << sum << endl;
    return 0;
}`,
    description: 'In Tamil Nadu 11th CS Chapter 10 (Flow of Control), what is the output of the switch-case construct when `break` statements are omitted?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Sum = 20',
      'Sum = 55',
      'Sum = 50',
      'Sum = 65'
    ],
    correctOptionIndex: 1,
    explanation: 'Because val is 2, execution jumps to case 2 (`sum += 20`). Since there are no break statements, execution falls through case 3 (`sum += 30`) and default (`sum += 5`), totaling 20 + 30 + 5 = 55.',
    hint: 'When a matching case lacks a break statement, fall-through occurs into all subsequent cases.'
  },
  {
    id: 'q3',
    qNumber: 3,
    syllabusStandard: '11th',
    topic: 'C++ Functions: Call by Reference with Alias',
    language: 'C++',
    title: 'Question 3: Reference Parameters vs Value Passing',
    codeSnippet: `#include <iostream>
using namespace std;

void modify(int &x, int y) {
    x = x + 10;
    y = y + 20;
}

int main() {
    int p = 5, q = 15;
    modify(p, q);
    cout << p << " " << q << endl;
    return 0;
}`,
    description: 'Examine the function `modify(int &x, int y)`. Predict the output printed by the `main()` function in C++.',
    type: 'multiple_choice',
    points: 3,
    options: [
      '15 15',
      '15 35',
      '5 15',
      '5 35'
    ],
    correctOptionIndex: 0,
    explanation: '`x` is passed by reference (`int &x`), modifying `p` in-place to `5 + 10 = 15`. `y` is passed by value, so changes to `y` do not affect `q`. Output is `15 15`.',
    hint: 'The ampersand `&` indicates an alias/reference to the original caller variable.'
  },
  {
    id: 'q4',
    qNumber: 4,
    syllabusStandard: '11th',
    topic: 'C++ Functions: Default Arguments Order',
    language: 'C++',
    title: 'Question 4: Default Arguments in C++ Function Prototypes',
    codeSnippet: `#include <iostream>
using namespace std;

int calculate(int x, int y = 4, int z = 2) {
    return (x * y) - z;
}

int main() {
    cout << calculate(5, 3) << " " << calculate(6) << endl;
    return 0;
}`,
    description: 'What output is generated by calling `calculate(5, 3)` and `calculate(6)`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '13 22',
      '15 24',
      '13 24',
      '11 22'
    ],
    correctOptionIndex: 0,
    explanation: '`calculate(5, 3)` uses `x=5, y=3, z=2` default -> `(5*3)-2 = 13`. `calculate(6)` uses `x=6, y=4, z=2` defaults -> `(6*4)-2 = 22`.',
    hint: 'Missing trailing arguments are filled in from right to left using the default values.'
  },
  {
    id: 'q5',
    qNumber: 5,
    syllabusStandard: '11th',
    topic: 'C++ 2D Arrays: Memory Offset Calculation',
    language: 'C++',
    title: 'Question 5: Two-Dimensional Array Traversal',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int matrix[2][3] = {{1, 2, 3}, {4, 5, 6}};
    int sum = 0;
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 3; j++) {
            if (i == j) sum += matrix[i][j];
        }
    }
    cout << "Trace Sum = " << sum << endl;
    return 0;
}`,
    description: 'What is the value of `sum` after iterating through the 2x3 matrix where `i == j`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Trace Sum = 6',
      'Trace Sum = 7',
      'Trace Sum = 9',
      'Trace Sum = 1'
    ],
    correctOptionIndex: 0,
    explanation: 'The matching indices are `(0,0)` which has value 1, and `(1,1)` which has value 5. Therefore `sum = 1 + 5 = 6`.',
    hint: 'Check matrix[0][0] and matrix[1][1].'
  },
  {
    id: 'q6',
    qNumber: 6,
    syllabusStandard: '11th',
    topic: 'C++ Classes & Objects: Private Access Specifiers',
    language: 'C++',
    title: 'Question 6: Encapsulation and Data Member Scope',
    codeSnippet: `#include <iostream>
using namespace std;

class Student {
    int rollNo; // default access specifier
public:
    void setRoll(int r) { rollNo = r; }
    int getRoll() { return rollNo; }
};

int main() {
    Student s;
    s.setRoll(101);
    cout << s.getRoll() << endl;
    return 0;
}`,
    description: 'In C++ class definitions (TN 11th CS Chapter 14), what is the default access specifier for class members if none is specified?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'private (101 is printed correctly via public accessor)',
      'public (rollNo is directly accessible globally)',
      'protected (only derived classes can access)',
      'Compile error because rollNo cannot be accessed inside member function'
    ],
    correctOptionIndex: 0,
    explanation: 'In C++, members of a class are `private` by default. Member functions within the class (`setRoll` and `getRoll`) can freely access `rollNo`, so 101 is printed.',
    hint: 'By default, C++ class members are private, while struct members are public.'
  },
  {
    id: 'q7',
    qNumber: 7,
    syllabusStandard: '11th',
    topic: 'C++ Constructors & Destructors Execution Order',
    language: 'C++',
    title: 'Question 7: Stack Unwinding and Destructor Invocation Order',
    codeSnippet: `#include <iostream>
using namespace std;

class Tracker {
    int id;
public:
    Tracker(int n) : id(n) { cout << "C" << id; }
    ~Tracker() { cout << "D" << id; }
};

int main() {
    Tracker t1(1);
    {
        Tracker t2(2);
    }
    Tracker t3(3);
    return 0;
}`,
    description: 'What exact character sequence is displayed on stdout as objects enter and exit scope in C++?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'C1C2D2C3D3D1',
      'C1C2C3D3D2D1',
      'C1C2D2C3D1D3',
      'C1D1C2D2C3D3'
    ],
    correctOptionIndex: 0,
    explanation: '1. `t1(1)` constructs -> `C1`. 2. Inner block `t2(2)` constructs -> `C2`. 3. Inner block ends, `t2` destructs -> `D2`. 4. `t3(3)` constructs -> `C3`. 5. `main` exits, destroying `t3` -> `D3`, then `t1` -> `D1` (reverse order of creation). Output: `C1C2D2C3D3D1`.',
    hint: 'Destructors are called in reverse order of construction (LIFO) when their enclosing scope ends.'
  },
  {
    id: 'q8',
    qNumber: 8,
    syllabusStandard: '11th',
    topic: 'C++ Inheritance: Multiple Inheritance Constructor Order',
    language: 'C++',
    title: 'Question 8: Constructor Calling Order in Derived Classes',
    codeSnippet: `#include <iostream>
using namespace std;

class Alpha {
public:
    Alpha() { cout << "A"; }
};

class Beta {
public:
    Beta() { cout << "B"; }
};

class Gamma : public Beta, public Alpha {
public:
    Gamma() { cout << "G"; }
};

int main() {
    Gamma obj;
    return 0;
}`,
    description: 'According to Tamil Nadu 11th CS Chapter 16 (Inheritance), what is the constructor execution order when instantiating `Gamma`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'BAG',
      'ABG',
      'GBA',
      'GAB'
    ],
    correctOptionIndex: 0,
    explanation: 'In multiple inheritance, base class constructors execute in the order they are listed in the class derivation header (`public Beta, public Alpha`). So `Beta` runs first ("B"), then `Alpha` ("A"), then `Gamma` ("G") -> `BAG`.',
    hint: 'Constructors of base classes are invoked in the order of their declaration in the inheritance list.'
  },
  {
    id: 'q9',
    qNumber: 9,
    syllabusStandard: '11th',
    topic: 'C++ Polymorphism: Operator Overloading',
    language: 'C++',
    title: 'Question 9: Unary Operator Overloading',
    codeSnippet: `#include <iostream>
using namespace std;

class Counter {
    int count;
public:
    Counter(int c = 0) : count(c) {}
    void operator++() {
        count += 5;
    }
    void display() { cout << "Count: " << count << endl; }
};

int main() {
    Counter c(10);
    ++c;
    c.display();
    return 0;
}`,
    description: 'What will be output by calling `++c` with the overloaded prefix operator method?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Count: 15',
      'Count: 11',
      'Count: 10',
      'Compilation Error: Cannot overload ++'
    ],
    correctOptionIndex: 0,
    explanation: 'The overloaded `operator++()` increments the internal `count` by 5. Starting at 10, `10 + 5 = 15`.',
    hint: 'Look at what the operator++ function body does (`count += 5`).'
  },
  {
    id: 'q10',
    qNumber: 10,
    syllabusStandard: '11th',
    topic: 'C++ Pointers: Pointer Arithmetic & Dereferencing',
    language: 'C++',
    title: 'Question 10: Pointer Dereferencing with Arrays',
    codeSnippet: `#include <iostream>
using namespace std;

int main() {
    int arr[] = {10, 20, 30, 40, 50};
    int *ptr = arr;
    ptr += 2;
    cout << *ptr << " " << *(ptr + 1) << endl;
    return 0;
}`,
    description: 'What numbers are printed by `*ptr` and `*(ptr + 1)` after the pointer shift?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '30 40',
      '20 30',
      '30 50',
      '40 50'
    ],
    correctOptionIndex: 0,
    explanation: '`arr` points to element at index 0 (10). `ptr += 2` shifts the pointer to index 2 (30). `*ptr` is 30, and `*(ptr + 1)` is index 3 (40).',
    hint: 'Pointer addition moves through array elements in steps of the data type size.'
  },
  {
    id: 'q11',
    qNumber: 11,
    syllabusStandard: '11th',
    topic: 'C++ Strings: Built-in C-String Functions',
    language: 'C++',
    title: 'Question 11: String Concatenation & Length in C-Strings',
    codeSnippet: `#include <iostream>
#include <cstring>
using namespace std;

int main() {
    char str1[20] = "Tamil";
    char str2[] = "Nadu";
    strcat(str1, str2);
    cout << strlen(str1) << " " << str1 << endl;
    return 0;
}`,
    description: 'What does `strlen(str1)` return after `strcat(str1, str2)` operates on the strings?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '9 TamilNadu',
      '10 TamilNadu',
      '20 TamilNadu',
      '5 Tamil'
    ],
    correctOptionIndex: 0,
    explanation: '`strcat` appends "Nadu" to "Tamil", resulting in "TamilNadu". `strlen("TamilNadu")` is 5 + 4 = 9 characters (excluding null terminator `\\0`).',
    hint: 'strlen counts the number of characters before the null terminator.'
  },
  {
    id: 'q12',
    qNumber: 12,
    syllabusStandard: '11th',
    topic: 'C++ Recursion: Factorial Base Case Execution',
    language: 'C++',
    title: 'Question 12: Recursive Function Call Stack',
    codeSnippet: `#include <iostream>
using namespace std;

int fun(int n) {
    if (n <= 1) return 1;
    return n + fun(n - 2);
}

int main() {
    cout << fun(6) << endl;
    return 0;
}`,
    description: 'Compute the return value of `fun(6)` following the recursive evaluation path.',
    type: 'multiple_choice',
    points: 3,
    options: [
      '13',
      '12',
      '15',
      '6'
    ],
    correctOptionIndex: 0,
    explanation: '`fun(6) = 6 + fun(4) = 6 + (4 + fun(2)) = 6 + 4 + (2 + fun(0)) = 6 + 4 + 2 + 1 = 13` (since `fun(0)` hits base case `n <= 1` returning 1).',
    hint: 'Trace the stack: fun(6) -> 6 + fun(4) -> 4 + fun(2) -> 2 + fun(0).'
  },

  // ==================== 12TH STANDARD TN STATE BOARD CS (PYTHON, DBMS & INTEGRATION) ====================
  {
    id: 'q13',
    qNumber: 13,
    syllabusStandard: '12th',
    topic: 'Python Control Structures: Range Step Argument',
    language: 'Python',
    title: 'Question 13: Reverse Step Iteration in Python `range()`',
    codeSnippet: `total = 0
for i in range(10, 0, -3):
    total += i
print("Total =", total)`,
    description: 'In Tamil Nadu 12th CS Chapter 6 (Control Structures), what value is calculated by the loop iterating with step `-3`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Total = 22',
      'Total = 19',
      'Total = 25',
      'Total = 15'
    ],
    correctOptionIndex: 0,
    explanation: 'The loop produces values 10, 7, 4, 1 (since stop is 0, non-inclusive). `10 + 7 + 4 + 1 = 22`.',
    hint: 'Start at 10, subtract 3 each step until > 0: 10, 7, 4, 1.'
  },
  {
    id: 'q14',
    qNumber: 14,
    syllabusStandard: '12th',
    topic: 'Python Strings: Negative Step Slicing',
    language: 'Python',
    title: 'Question 14: String Slicing with Steps & Boundaries',
    codeSnippet: `text = "TAMILNADU"
slice1 = text[1:7:2]
slice2 = text[::-2]
print(slice1, slice2)`,
    description: 'What two sliced strings are printed by Python string indexing?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'AIN UAMAT',
      'AML UDNL',
      'AIN UDAMA',
      'AML UAMAT'
    ],
    correctOptionIndex: 0,
    explanation: '`text[1:7:2]`: indices 1 ("A"), 3 ("I"), 5 ("N") -> "AIN". `text[::-2]`: backwards from index 8 ("U"), 6 ("A"), 4 ("M"), 2 ("A"), 0 ("T") -> "UAMAT".',
    hint: 'Slice syntax is [start:stop:step]. Step 2 skips every second letter.'
  },
  {
    id: 'q15',
    qNumber: 15,
    syllabusStandard: '12th',
    topic: 'Python Lists: List Comprehension with Filter',
    language: 'Python',
    title: 'Question 15: List Comprehension and In-Place Aliasing',
    codeSnippet: `nums = [1, 2, 3, 4, 5, 6]
evens_squared = [x**2 for x in nums if x % 2 == 0]
print(evens_squared)`,
    description: 'What is the output of the list comprehension filtering even numbers and squaring them?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '[4, 16, 36]',
      '[1, 9, 25]',
      '[2, 4, 6]',
      '[4, 8, 12]'
    ],
    correctOptionIndex: 0,
    explanation: 'Even numbers in `nums` are 2, 4, 6. Squaring them yields `2**2=4, 4**2=16, 6**2=36` -> `[4, 16, 36]`.',
    hint: 'Only even numbers (2, 4, 6) satisfy x % 2 == 0.'
  },
  {
    id: 'q16',
    qNumber: 16,
    syllabusStandard: '12th',
    topic: 'Python Tuples & Sets: Immutability and Set Operations',
    language: 'Python',
    title: 'Question 16: Set Symmetric Difference and Set Operations',
    codeSnippet: `set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}
sym_diff = set_a ^ set_b
print(sorted(list(sym_diff)))`,
    description: 'According to Tamil Nadu 12th CS Chapter 9 (Lists, Tuples, Sets and Dictionaries), what is the result of the symmetric difference operator `^`?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '[1, 2, 5, 6]',
      '[3, 4]',
      '[1, 2, 3, 4, 5, 6]',
      '[1, 2]'
    ],
    correctOptionIndex: 0,
    explanation: 'Symmetric difference (`^`) returns elements in either set_a or set_b, but NOT in both (i.e. `(A ∪ B) - (A ∩ B)`). Common elements 3, 4 are excluded, leaving `{1, 2, 5, 6}`.',
    hint: 'Symmetric difference means elements in either set, but not in both.'
  },
  {
    id: 'q17',
    qNumber: 17,
    syllabusStandard: '12th',
    topic: 'Python Dictionaries: Keys, Values & `.get()` Default',
    language: 'Python',
    title: 'Question 17: Dictionary Lookup with Fallback Defaults',
    codeSnippet: `marks = {"CS": 98, "Maths": 95, "Physics": 92}
val1 = marks.get("Chemistry", 85)
val2 = marks.get("CS", 100)
print(val1 + val2)`,
    description: 'What sum is returned by invoking `.get()` with key defaults?',
    type: 'multiple_choice',
    points: 3,
    options: [
      '183',
      '198',
      '180',
      'KeyError: Chemistry not found'
    ],
    correctOptionIndex: 0,
    explanation: '"Chemistry" does not exist in `marks`, so `.get("Chemistry", 85)` returns the default 85. "CS" exists with value 98, so `.get("CS", 100)` returns 98. `85 + 98 = 183`.',
    hint: 'dict.get(key, default) returns the key value if found, else default without raising KeyError.'
  },
  {
    id: 'q18',
    qNumber: 18,
    syllabusStandard: '12th',
    topic: 'Python OOP: Class Variables vs Instance Variables',
    language: 'Python',
    title: 'Question 18: Class Attribute Mutation via Instance',
    codeSnippet: `class School:
    board = "TN State Board"
    def __init__(self, name):
        self.name = name

s1 = School("Chennai School")
s2 = School("Madurai School")
School.board = "TN SCERT Board"
s1.board = "Custom Board"

print(s1.board, s2.board)`,
    description: 'In Python OOP (TN 12th CS Chapter 10), how does instance attribute shadowing interact with class variables?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Custom Board TN SCERT Board',
      'TN SCERT Board TN SCERT Board',
      'Custom Board Custom Board',
      'TN State Board TN SCERT Board'
    ],
    correctOptionIndex: 0,
    explanation: '`s1.board = "Custom Board"` creates an instance attribute on `s1`, shadowing the class variable. `s2.board` still accesses the mutated class variable `School.board = "TN SCERT Board"`.',
    hint: 'Setting an attribute on an instance creates an instance-level attribute without changing other instances.'
  },
  {
    id: 'q19',
    qNumber: 19,
    syllabusStandard: '12th',
    topic: 'Python Variable Scope: Global & Nonlocal Keywords',
    language: 'Python',
    title: 'Question 19: Global Variable Scope Modification',
    codeSnippet: `count = 10

def increment():
    global count
    count += 5

def local_test():
    count = 50

increment()
local_test()
print("Final Count =", count)`,
    description: 'What is the final value of the global `count` variable after both functions execute?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Final Count = 15',
      'Final Count = 50',
      'Final Count = 10',
      'Final Count = 65'
    ],
    correctOptionIndex: 0,
    explanation: '`increment()` uses `global count` to update the global count to 15. `local_test()` assigns to a local variable `count = 50` which does not affect the global count.',
    hint: 'The global keyword binds the assignment to the module-level variable.'
  },
  {
    id: 'q20',
    qNumber: 20,
    syllabusStandard: '12th',
    topic: 'Python CSV Module: DictReader Delimiters',
    language: 'Python',
    title: 'Question 20: Processing CSV Files with Python `csv` Module',
    codeSnippet: `import csv
# Suppose data.csv contains:
# Roll,Name,Marks
# 101,Anitha,96
# 102,Bala,89

total = 0
# Code snippet logic:
rows = [{"Roll": "101", "Marks": "96"}, {"Roll": "102", "Marks": "89"}]
for r in rows:
    total += int(r["Marks"])
print("Average =", total / len(rows))`,
    description: 'In Tamil Nadu 12th CS Chapter 13 (Python and CSV Files), what average mark is computed from the CSV rows?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Average = 92.5',
      'Average = 93.0',
      'Average = 92.0',
      'TypeError: cannot convert str to int'
    ],
    correctOptionIndex: 0,
    explanation: '`(96 + 89) = 185`. `185 / 2 = 92.5`.',
    hint: 'Remember that CSV reader values are read as strings and must be cast with int().'
  },
  {
    id: 'q21',
    qNumber: 21,
    syllabusStandard: '12th',
    topic: 'DBMS: Relational SQL Queries & Aggregate Functions',
    language: 'SQL',
    title: 'Question 21: SQL GROUP BY with HAVING Filter',
    codeSnippet: `-- Schema: STUDENTS (RollNo, Dept, Marks)
SELECT Dept, AVG(Marks) AS AvgMarks
FROM STUDENTS
GROUP BY Dept
HAVING COUNT(*) >= 2;`,
    description: 'In Tamil Nadu 12th CS Chapter 12 (Structured Query Language), what does the `HAVING` clause filter?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Groups of departments that have 2 or more students',
      'Individual student rows before grouping',
      'Only departments whose average mark is greater than 2',
      'Syntax error: HAVING cannot be used with COUNT(*)'
    ],
    correctOptionIndex: 0,
    explanation: '`WHERE` filters individual rows before grouping, while `HAVING` filters aggregated group records. `HAVING COUNT(*) >= 2` restricts output to departments having 2 or more student records.',
    hint: 'HAVING is used to filter groups created by the GROUP BY clause.'
  },
  {
    id: 'q22',
    qNumber: 22,
    syllabusStandard: '12th',
    topic: 'DBMS SQL: String Pattern Matching with LIKE',
    language: 'SQL',
    title: 'Question 22: SQL Wildcard Characters `%` and `_`',
    codeSnippet: `-- Find student names
SELECT StudentName
FROM STUDENTS
WHERE StudentName LIKE 'K__a%';`,
    description: 'Which of the following student names will match the pattern `\'K__a%\'` (where `_` is a single char wildcard and `%` matches zero or more chars)?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Kavya (Starts with K, 2 chars "av", followed by "a", then "ya")',
      'Kala (Only 1 char between K and l)',
      'Kumar (Does not have "a" at the 4th position)',
      'K (Too short)'
    ],
    correctOptionIndex: 0,
    explanation: '`K__a%` requires: 1st char = \'K\', 2nd & 3rd chars = any 2 characters (`__`), 4th char = \'a\', followed by any number of characters (`%`). In "Kavya": K(1), a(2), v(3), a(4), ya(5-6) -> MATCHES.',
    hint: 'Underscore `_` represents exactly one character; percent `%` represents zero or more characters.'
  },
  {
    id: 'q23',
    qNumber: 23,
    syllabusStandard: '12th',
    topic: 'Python SQLite3 / Database Connection API',
    language: 'Python',
    title: 'Question 23: Python SQLite Database Query Fetching',
    codeSnippet: `import sqlite3
# Assuming connection 'conn' and cursor 'cur':
# Table has 5 student records
# cur.execute("SELECT * FROM Student WHERE Marks > 80")
# 3 students qualify.
# res = cur.fetchmany(2)
# print(len(res))`,
    description: 'In Tamil Nadu 12th CS Chapter 15 (Data Manipulation through SQL), what is returned by `cur.fetchmany(2)` when 3 records qualify?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'A list containing exactly 2 record tuples',
      'A list containing all 3 record tuples',
      'An integer count 2',
      'A single record tuple'
    ],
    correctOptionIndex: 0,
    explanation: '`fetchmany(size)` fetches the next set of rows of a query result, returning a list of tuples up to `size` (here 2).',
    hint: 'fetchmany(size) limits the returned records to the requested number.'
  },
  {
    id: 'q24',
    qNumber: 24,
    syllabusStandard: '12th',
    topic: 'Python & C++ Integration (MinGW / System Call)',
    language: 'Python',
    title: 'Question 24: Executing C++ Executables from Python Scripts',
    codeSnippet: `import os, sys
# Chapter 15: Integrating C++ with Python
# Command to compile C++ program 'prog.cpp' using g++:
cmd = "g++ prog.cpp -o prog.exe"
status = os.system(cmd)
# If compilation succeeds:
print("Exit Status =", status)`,
    description: 'In TN 12th CS Chapter 15 (Importing C++ Programs in Python), what integer exit status is returned by `os.system()` when compilation succeeds without errors?',
    type: 'multiple_choice',
    points: 3,
    options: [
      'Exit Status = 0',
      'Exit Status = 1',
      'Exit Status = -1',
      'Exit Status = 200'
    ],
    correctOptionIndex: 0,
    explanation: 'In operating systems and POSIX/Windows CLI tools, an exit status of 0 represents successful execution with zero errors.',
    hint: 'In shell systems, 0 indicates success, non-zero indicates an error.'
  },

  // ==================== QUESTION 25: PROMPT TYPE (BUILD A WEBSITE) ====================
  {
    id: 'q25',
    qNumber: 25,
    syllabusStandard: 'WebDev',
    topic: 'Modern Web Development: HTML5, Tailwind/CSS & JavaScript Interactive Application',
    language: 'HTML/CSS/JS',
    title: 'Question 25: Build a website on your favourite theme. Give me your prompt',
    description: `🚀 **Website Builder Challenge**: Build a website on your favourite theme. Give me your prompt.

Type your detailed prompt into the typebox below. Describe your chosen theme, UI design, components, color scheme, interactive behaviors, and features. You can also build and preview the corresponding web code in the interactive sandbox below!`,
    type: 'website_prompt',
    points: 28,
    websiteTemplate: {
      html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Favorite Theme Website</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 font-sans p-6 min-h-screen flex items-center justify-center">
  <div class="max-w-2xl w-full bg-slate-900 border border-cyan-500/30 rounded-3xl p-8 shadow-2xl text-center space-y-4">
    <div class="w-16 h-16 rounded-2xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center mx-auto text-3xl font-bold">
      ✨
    </div>
    <h1 class="text-3xl font-black text-white font-orbitron">My Favourite Theme Website</h1>
    <p class="text-slate-400 text-sm">Enter your prompt in the typebox above to describe and build your custom website.</p>
  </div>
</body>
</html>`,
      css: `/* Custom CSS Enhancements */
body {
  font-family: system-ui, -apple-system, sans-serif;
}`,
      js: `console.log("Website initialized.");`
    },
    hint: 'Give your detailed prompt describing your favorite theme, components, user interactions, and visual styling.'
  }
];

export const INITIAL_CANDIDATE_SUBMISSIONS: CandidateSubmission[] = [];

export const INITIAL_EMAIL_NOTIFICATIONS: EmailNotification[] = [];

